//
// Generated file, do not edit! Created by opp_msgtool 6.0 from Network/Packet/DetailedResultChunk.msg.
//

#ifndef __DETAILEDRESULTCHUNK_M_H
#define __DETAILEDRESULTCHUNK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DetailedResultChunk;
#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

// cplusplus {{
#include "inet/common/packet/chunk/FieldsChunk.h"
// }}

/**
 * Class generated from <tt>Network/Packet/DetailedResultChunk.msg:25</tt> by opp_msgtool.
 * <pre>
 * class DetailedResultChunk extends inet::FieldsChunk
 * {
 *     string data = "";
 *     string details = "";
 *     int Sumresults = 0;
 *     bool isEven = false;
 *     string sentBy = "";
 * 
 * 
 * }
 * </pre>
 */
class DetailedResultChunk : public ::inet::FieldsChunk
{
  protected:
    omnetpp::opp_string data = "";
    omnetpp::opp_string details = "";
    int Sumresults = 0;
    bool isEven_ = false;
    omnetpp::opp_string sentBy = "";

  private:
    void copy(const DetailedResultChunk& other);

  protected:
    bool operator==(const DetailedResultChunk&) = delete;

  public:
    DetailedResultChunk();
    DetailedResultChunk(const DetailedResultChunk& other);
    virtual ~DetailedResultChunk();
    DetailedResultChunk& operator=(const DetailedResultChunk& other);
    virtual DetailedResultChunk *dup() const override {return new DetailedResultChunk(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getData() const;
    virtual void setData(const char * data);

    virtual const char * getDetails() const;
    virtual void setDetails(const char * details);

    virtual int getSumresults() const;
    virtual void setSumresults(int Sumresults);

    virtual bool isEven() const;
    virtual void setIsEven(bool isEven);

    virtual const char * getSentBy() const;
    virtual void setSentBy(const char * sentBy);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DetailedResultChunk& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DetailedResultChunk& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DetailedResultChunk *fromAnyPtr(any_ptr ptr) { return check_and_cast<DetailedResultChunk*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DETAILEDRESULTCHUNK_M_H

