//
// Generated file, do not edit! Created by opp_msgtool 6.0 from Network/Packet/HelloPacket.msg.
//

#ifndef __HELLOPACKET_M_H
#define __HELLOPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class HelloPacket;
#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

// cplusplus {{
#include "inet/common/packet/chunk/FieldsChunk.h"
// }}

/**
 * Class generated from <tt>Network/Packet/HelloPacket.msg:23</tt> by opp_msgtool.
 * <pre>
 * class HelloPacket extends inet::FieldsChunk
 * {
 *     string data = "";
 *     int sourcePort = -1;
 *     int destinationPort = -1;
 *     int x = 0;
 *     int y = 0;
 * 
 * }
 * </pre>
 */
class HelloPacket : public ::inet::FieldsChunk
{
  protected:
    omnetpp::opp_string data = "";
    int sourcePort = -1;
    int destinationPort = -1;
    int x = 0;
    int y = 0;

  private:
    void copy(const HelloPacket& other);

  protected:
    bool operator==(const HelloPacket&) = delete;

  public:
    HelloPacket();
    HelloPacket(const HelloPacket& other);
    virtual ~HelloPacket();
    HelloPacket& operator=(const HelloPacket& other);
    virtual HelloPacket *dup() const override {return new HelloPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getData() const;
    virtual void setData(const char * data);

    virtual int getSourcePort() const;
    virtual void setSourcePort(int sourcePort);

    virtual int getDestinationPort() const;
    virtual void setDestinationPort(int destinationPort);

    virtual int getX() const;
    virtual void setX(int x);

    virtual int getY() const;
    virtual void setY(int y);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HelloPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HelloPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline HelloPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<HelloPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __HELLOPACKET_M_H

