//
// Generated file, do not edit! Created by opp_msgtool 6.0 from Network/Packet/SumPacket.msg.
//

#ifndef __SUMPACKET_M_H
#define __SUMPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class SumPacket;
#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

// cplusplus {{
#include "inet/common/packet/chunk/FieldsChunk.h"
// }}

/**
 * Class generated from <tt>Network/Packet/SumPacket.msg:21</tt> by opp_msgtool.
 * <pre>
 * class SumPacket extends inet::FieldsChunk
 * {
 *     string data = "";
 *     int sourcePort = -1;
 *     int destinationPort = -1;
 *     string senderName = "";
 *     string recieverName = "";
 *     bool isTest = false;
 * }
 * </pre>
 */
class SumPacket : public ::inet::FieldsChunk
{
  protected:
    omnetpp::opp_string data = "";
    int sourcePort = -1;
    int destinationPort = -1;
    omnetpp::opp_string senderName = "";
    omnetpp::opp_string recieverName = "";
    bool isTest_ = false;

  private:
    void copy(const SumPacket& other);

  protected:
    bool operator==(const SumPacket&) = delete;

  public:
    SumPacket();
    SumPacket(const SumPacket& other);
    virtual ~SumPacket();
    SumPacket& operator=(const SumPacket& other);
    virtual SumPacket *dup() const override {return new SumPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getData() const;
    virtual void setData(const char * data);

    virtual int getSourcePort() const;
    virtual void setSourcePort(int sourcePort);

    virtual int getDestinationPort() const;
    virtual void setDestinationPort(int destinationPort);

    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);

    virtual const char * getRecieverName() const;
    virtual void setRecieverName(const char * recieverName);

    virtual bool isTest() const;
    virtual void setIsTest(bool isTest);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SumPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SumPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline SumPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<SumPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SUMPACKET_M_H

